# Generated by Django 5.0.1 on 2025-01-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='scanned_qr_codes',
            field=models.ManyToManyField(blank=True, related_name='pickup_requests', to='homepage.qrcode'),
        ),
    ]
