# Generated by Django 5.0.1 on 2024-12-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Picked Up', 'Picked Up'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
