# Generated by Django 5.0.1 on 2025-01-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_pickuprequest_scanned_qr_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='num_bags',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
