# Generated by Django 5.0.1 on 2025-01-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_pickuprequest_num_bags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='scanned_qr_codes',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='scanned_bag_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
